# Generated by Django 5.2.1 on 2025-05-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_add_group_to_user", "Can add groups to a user")],
            },
        ),
    ]
