# Generated by Django 5.2.1 on 2025-05-21 22:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.FileField(upload_to="uploads/")),
                (
                    "type_file",
                    models.CharField(
                        choices=[("image", "Imagem"), ("attachment", "Anexo")],
                        db_index=True,
                        max_length=100,
                    ),
                ),
            ],
            options={
                "db_table": "file",
                "ordering": ["created_at"],
            },
        ),
    ]
