
services:
  db-jota:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=jota_dev
      - POSTGRES_USER=JotaUser
      - POSTGRES_PASSWORD=JotaUserPassword
    volumes:
      - data_jota_database:/var/lib/postgresql/data/
    ports:
      - "5438:5432"

volumes:
  data_jota_database: