# Generated by Django 5.2.1 on 2025-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("published", "published"),
                    ("archived", "archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
