name: Django API application

on: pull_request

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    env:
      ALLOWED_HOSTS: "http://localhost,http://127.0.0.1"
      DATABASE: "default"
      SECRET_KEY: "fake-key-for-ci"
      SQL_DATABASE: "ci_db"
      SQL_ENGINE: "django.db.backends.postgresql"
      SQL_HOST: "localhost"
      SQL_PASSWORD: "postgres"
      SQL_PORT: "5432"
      SQL_USER: "postgres"
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ci_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            **/requirements.txt

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          pytest -v --disable-warnings --cov
