name: Django API application

on: pull_request

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ci_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Setup python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
      - name : Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          ALLOWED_HOSTS: "localhost,127.0.0.1"
          DATABASE: ${{ secrets.DATABASE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
          SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
          SQL_HOST: ${{ secrets.SQL_HOST }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_PORT: ${{ secrets.SQL_PORT }}
          SQL_USER: ${{ secrets.SQL_USER }}
      - name: Run migrations
        run: |
          python manage.py migrate
      - name: Run tests
        run: |
          pytest -v --disable-warnings --cov